import java.util.Scanner;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SECPC106
 */
public class RandomFour {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
    //Guess the number generated by Math.random, the range is from 1 to 50. outpt "correct" if the the user guesses
    // and not correct if the user doesn't guess
    Scanner scn = new Scanner(System.in);
     int x = (int)(Math.random()*50+1);
     
     System.out.print("Guess the number: ");
     int num = scn.nextInt();
     
     if(num == x)
     {
         System.out.print("Correct");    
    }
     else{
             System.out.print("Not correct! The number was: " + x);
             }
     
     
    }
    
}
